/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicImageStudioRouteImport } from './routes/api/public/image-studio'
import { Route as ApiPublicTelegramOrderRouteImport } from './routes/api/public/telegram-order'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageStudioRoute = ApiPublicImageStudioRouteImport.update({
  id: '/api/public/image-studio',
  path: '/api/public/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramOrderRoute = ApiPublicTelegramOrderRouteImport.update({
  id: '/api/public/telegram-order',
  path: '/api/public/telegram-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/image-studio': typeof ApiPublicImageStudioRoute
  '/api/public/telegram-order': typeof ApiPublicTelegramOrderRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/image-studio': typeof ApiPublicImageStudioRoute
  '/api/public/telegram-order': typeof ApiPublicTelegramOrderRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/image-studio': typeof ApiPublicImageStudioRoute
  '/api/public/telegram-order': typeof ApiPublicTelegramOrderRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/image-studio'
    | '/api/public/telegram-order'
    | '/api/public/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/image-studio'
    | '/api/public/telegram-order'
    | '/api/public/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/api/public/image-studio'
    | '/api/public/telegram-order'
    | '/api/public/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicImageStudioRoute: typeof ApiPublicImageStudioRoute
  ApiPublicTelegramOrderRoute: typeof ApiPublicTelegramOrderRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image-studio': {
      id: '/api/public/image-studio'
      path: '/api/public/image-studio'
      fullPath: '/api/public/image-studio'
      preLoaderRoute: typeof ApiPublicImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-order': {
      id: '/api/public/telegram-order'
      path: '/api/public/telegram-order'
      fullPath: '/api/public/telegram-order'
      preLoaderRoute: typeof ApiPublicTelegramOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicImageStudioRoute: ApiPublicImageStudioRoute,
  ApiPublicTelegramOrderRoute: ApiPublicTelegramOrderRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
